<script setup>
import NexxworthLayout from '@/Layouts/NexxworthLayout.vue';
</script>
<template>
    <NexxworthLayout>
        <section class="bg-[#10223a] text-white"><div class="mx-auto max-w-7xl px-5 py-16 sm:px-8 lg:py-20"><p class="text-xs font-bold uppercase tracking-[0.22em] text-[#ee938a]">Data protection</p><h1 class="mt-5 [font-family:Georgia,serif] text-5xl sm:text-6xl">Privacy notice</h1><p class="mt-5 max-w-2xl text-base leading-8 text-[#d2dfeb]">Information about the processing of personal data under Regulation (EU) 2016/679.</p></div></section>
        <section class="mx-auto max-w-4xl px-5 py-16 sm:px-8 lg:py-20"><div class="space-y-10 rounded-[2rem] border border-[#e1e6e8] bg-white p-7 text-base leading-8 text-[#455b70] shadow-sm sm:p-12"><div><h2 class="text-2xl font-bold text-[#132b47]">Data controller</h2><p class="mt-3">Nexxworth Consulting di Singh Kamaljeet, Via Cremona 29/A int. 3, 46100 Mantova (MN), Italy, VAT no. 02553520202. For questions about your data, email <a href="mailto:ksd.servizi@gmail.com" class="font-semibold text-[#194a79] underline">ksd.servizi@gmail.com</a>.</p></div><div><h2 class="text-2xl font-bold text-[#132b47]">Data and purposes</h2><p class="mt-3">When you contact us, we may receive your name, contact details and information in your message. We use these to respond to you and, where needed, manage requested services, customer records, service communications and legal obligations. Promotional communications require a separate legal basis.</p></div><div><h2 class="text-2xl font-bold text-[#132b47]">Legal basis</h2><p class="mt-3">Processing needed to respond and provide services is based on steps requested before entering into a contract or on performance of a contract. Applicable law governs mandatory requirements. Where special categories of data are necessary for a specific case, they are processed under the conditions set out in the GDPR.</p></div><div><h2 class="text-2xl font-bold text-[#132b47]">Recipients and retention</h2><p class="mt-3">Authorized staff and partners may access data. Professionals and other parties involved in a requested service or legal obligation may receive it where necessary. Data is not made public. It is kept for as long as needed for the purposes collected and applicable legal obligations.</p></div><div><h2 class="text-2xl font-bold text-[#132b47]">Your rights</h2><p class="mt-3">You may request access, correction, deletion or restriction of your data, exercise portability where applicable and object where the law allows. You may complain to the <a href="https://www.garanteprivacy.it/" target="_blank" rel="noopener noreferrer" class="font-semibold text-[#194a79] underline">Italian Data Protection Authority</a>. Contact the controller at the email above to exercise your rights.</p></div><div><h2 class="text-2xl font-bold text-[#132b47]">Cookies and external links</h2><p class="mt-3">This site uses technical features needed for navigation and submitting requests. External services such as maps and WhatsApp open only when you choose to use their links and are governed by their own privacy notices.</p></div><a :href="route('nexxworth.en.contact')" class="inline-flex min-h-[44px] items-center rounded-full bg-[#194a79] px-6 py-2 text-sm font-bold text-white">Back to contact</a></div></section>
    </NexxworthLayout>
</template>
