<script setup>
import { ArrowRightIcon, ChatBubbleLeftRightIcon, GlobeEuropeAfricaIcon, LightBulbIcon } from '@heroicons/vue/24/outline';
import NexxworthLayout from '@/Layouts/NexxworthLayout.vue';
</script>

<template>
    <NexxworthLayout>
        <section class="bg-[#10223a] text-white"><div class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><p class="text-xs font-bold uppercase tracking-[0.22em] text-[#ee938a]">La nostra storia</p><h1 class="mt-5 max-w-4xl [font-family:Georgia,serif] text-5xl leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Ogni percorso comincia con qualcuno che ascolta.</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-[#d2dfeb]">Esperienza vissuta, attenzione alle persone e indicazioni pratiche: è da qui che nasce Nexxworth Consulting.</p></div></section>

        <section class="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:gap-20 lg:py-28">
            <div class="overflow-hidden rounded-[2rem] bg-[#e5edf1]"><img src="/brand/nexxworth/italy-consulting.webp" alt="Simboli dell'Italia e strumenti di consulenza" class="aspect-[4/5] w-full object-cover" width="1024" height="603" /></div>
            <div><p class="text-xs font-bold uppercase tracking-[0.22em] text-[#b5322e]">Perché esistiamo</p><h2 class="mt-4 [font-family:Georgia,serif] text-4xl leading-tight text-[#132b47] sm:text-5xl">Una guida nata da un’esperienza personale.</h2><p class="mt-7 text-base leading-8 text-[#455b70]">Trasferirsi in un ambiente nuovo può significare imparare una lingua, capire regole sconosciute e trovare il proprio posto. Il fondatore di Nexxworth ha vissuto in prima persona queste difficoltà: da questa esperienza è nata la volontà di aiutare altre persone nel loro percorso.</p><p class="mt-5 text-base leading-8 text-[#455b70]">Offriamo consulenza calibrata sulle esigenze di persone e imprese, con particolare attenzione a immigrazione, trasferimento e adattamento culturale. Lavoriamo per rendere i passaggi complessi più comprensibili e affrontabili.</p><a :href="route('nexxworth.contact')" class="mt-8 inline-flex min-h-[48px] items-center gap-2 rounded-full bg-[#b5322e] px-6 py-3 text-sm font-bold text-white transition hover:bg-[#922925]">Parla con noi <ArrowRightIcon class="h-4 w-4" aria-hidden="true" /></a></div>
        </section>

        <section class="bg-[#eaf0f3]"><div class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-24"><div class="max-w-2xl"><p class="text-xs font-bold uppercase tracking-[0.22em] text-[#b5322e]">Come lavoriamo</p><h2 class="mt-4 [font-family:Georgia,serif] text-4xl leading-tight text-[#132b47] sm:text-5xl">La collaborazione fa la differenza.</h2></div><div class="mt-10 grid gap-5 md:grid-cols-3"><article class="rounded-[1.75rem] bg-white p-7"><ChatBubbleLeftRightIcon class="h-9 w-9 text-[#194a79]" aria-hidden="true" /><h3 class="mt-7 text-xl font-bold">Ascolto</h3><p class="mt-3 text-sm leading-7 text-[#52657a]">Partiamo dalla tua situazione, dalle domande che hai e dall’obiettivo che vuoi raggiungere.</p></article><article class="rounded-[1.75rem] bg-white p-7"><LightBulbIcon class="h-9 w-9 text-[#194a79]" aria-hidden="true" /><h3 class="mt-7 text-xl font-bold">Indicazioni chiare</h3><p class="mt-3 text-sm leading-7 text-[#52657a]">Traduciamo procedure e requisiti in passaggi pratici, senza perdere di vista i dettagli.</p></article><article class="rounded-[1.75rem] bg-white p-7"><GlobeEuropeAfricaIcon class="h-9 w-9 text-[#194a79]" aria-hidden="true" /><h3 class="mt-7 text-xl font-bold">Prospettiva internazionale</h3><p class="mt-3 text-sm leading-7 text-[#52657a]">Mettiamo in relazione persone, culture e servizi per facilitare il tuo percorso in Italia.</p></article></div></div></section>
    </NexxworthLayout>
</template>
