<script setup>
import { ArrowRightIcon, CalculatorIcon, DocumentCheckIcon, DocumentTextIcon, GlobeEuropeAfricaIcon, LanguageIcon } from '@heroicons/vue/24/outline';
import NexxworthLayout from '@/Layouts/NexxworthLayout.vue';

const services = [
    { number: '01', title: 'Assistenza burocratica', icon: DocumentTextIcon, text: 'Informazioni e orientamento per chi vive in Italia e deve affrontare pratiche amministrative, accesso ai servizi e nuovi passaggi della vita quotidiana.' },
    { number: '02', title: 'Domande di visto', icon: GlobeEuropeAfricaIcon, text: 'Supporto nella preparazione della documentazione per le richieste di visto, con attenzione ai requisiti e ai passaggi della domanda.' },
    { number: '03', title: 'Traduzioni e legalizzazioni', icon: LanguageIcon, text: 'Assistenza per traduzioni di documenti, legalizzazioni, autenticazioni e apostille quando servono per presentare una pratica.' },
    { number: '04', title: 'Ricongiungimento familiare', icon: DocumentCheckIcon, text: 'Orientamento nella richiesta di nulla osta e nei documenti necessari per il ricongiungimento con i propri familiari.' },
    { number: '05', title: 'Dichiarazioni fiscali e CAF', icon: CalculatorIcon, text: 'Aiuto nella compilazione delle dichiarazioni fiscali e negli altri adempimenti legati ai servizi CAF.' },
];
</script>

<template>
    <NexxworthLayout>
        <section class="bg-[#10223a] text-white"><div class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><p class="text-xs font-bold uppercase tracking-[0.22em] text-[#ee938a]">I nostri servizi</p><h1 class="mt-5 max-w-4xl [font-family:Georgia,serif] text-5xl leading-[1.08] tracking-tight sm:text-6xl lg:text-7xl">Soluzioni concrete per andare avanti.</h1><p class="mt-7 max-w-2xl text-lg leading-8 text-[#d2dfeb]">Un supporto per superare barriere linguistiche e burocratiche, accedere ai servizi e costruire il proprio percorso in Italia.</p></div></section>
        <section class="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28"><div class="grid gap-5 md:grid-cols-2"><article v-for="service in services" :key="service.number" class="rounded-[1.75rem] border border-[#e1e6e8] bg-white p-7 shadow-sm sm:p-9"><div class="flex items-start justify-between"><div class="grid h-14 w-14 place-items-center rounded-2xl bg-[#e9f0f5] text-[#194a79]"><component :is="service.icon" class="h-7 w-7" aria-hidden="true" /></div><span class="text-xs font-bold tracking-[0.15em] text-[#a8b7c5]">{{ service.number }}</span></div><h2 class="mt-8 text-2xl font-bold tracking-tight text-[#132b47]">{{ service.title }}</h2><p class="mt-4 text-base leading-8 text-[#52657a]">{{ service.text }}</p></article><article class="flex flex-col justify-between rounded-[1.75rem] bg-[#c43b34] p-7 text-white sm:p-9"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-[#ffe4df]">Una domanda specifica?</p><h2 class="mt-8 [font-family:Georgia,serif] text-3xl leading-tight">Partiamo dalla tua situazione.</h2><p class="mt-4 text-base leading-8 text-[#ffe7e3]">Raccontaci cosa ti serve: possiamo aiutarti a capire quale servizio è più adatto.</p></div><a :href="route('nexxworth.contact')" class="mt-8 inline-flex min-h-[48px] items-center gap-2 self-start rounded-full bg-white px-6 py-3 text-sm font-bold text-[#9b302b] transition hover:bg-[#f7e7e5]">Contattaci <ArrowRightIcon class="h-4 w-4" aria-hidden="true" /></a></article></div></section>
        <section class="bg-[#eaf0f3]"><div class="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-16 sm:px-8 lg:flex-row lg:items-center lg:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-[#b5322e]">Supporto linguistico</p><h2 class="mt-3 [font-family:Georgia,serif] text-3xl text-[#132b47]">Parliamo la lingua delle persone.</h2><p class="mt-3 text-sm leading-7 text-[#52657a]">Italiano, inglese, hindi, punjabi, francese e tedesco.</p></div><a :href="route('nexxworth.partners')" class="inline-flex min-h-[48px] items-center gap-2 self-start rounded-full border border-[#194a79] px-6 py-3 text-sm font-bold text-[#194a79] transition hover:bg-white">Scopri le collaborazioni <ArrowRightIcon class="h-4 w-4" aria-hidden="true" /></a></div></section>
    </NexxworthLayout>
</template>
